### ISSUE TITLE
Fedora Kurulum hatası

### ISSUE THREAD

**Issue by Caticer** [sulincix/debian-subsystem#1]
`[ket@ibrahim-laptop debian-subsystem]$ sudo make install DESTDIR=/
mkdir -p //usr/share/polkit-1/actions/ || true
install polkit/org.sulin.debian.policy //usr/share/polkit-1/actions/
mkdir -p //usr/bin/ || true
install cli/debian //usr/bin/debian
install cli/debian-umount //usr/bin/debian-umount
make -C utils install
make[1]: Entering directory '/home/ket/debian-subsystem/utils'
mkdir -p //usr/bin/ || true
install pidone //usr/bin/
install: 'pidone' durumlanamadı: Böyle bir dosya ya da dizin yok
make[1]: *** [Makefile:10: install] Error 1
make[1]: Leaving directory '/home/ket/debian-subsystem/utils'
make: *** [Makefile:19: install-core] Error 2
[ket@ibrahim-laptop debian-subsystem]$ `

**Comment by sulincix** [comment]
static olmadan derleyince çözülüyomuş.

Yalnız bole alpine çalışmayacak.
